[package]
name = "cobalt"
version = "0.0.1"
authors = ["Sorin Davidoi <sorin.davidoi@gmail.com>"]

[dependencies]
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
